// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: room_server.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Account;
@class Room;
@class Stream;
@class WndLayout;
@class XChatMessage;
@class XChatMessageAttachmemt;
GPB_ENUM_FWD_DECLARE(ConferenceRole);
GPB_ENUM_FWD_DECLARE(DeviceState);
GPB_ENUM_FWD_DECLARE(HandUpStatus);
GPB_ENUM_FWD_DECLARE(McuStatus);
GPB_ENUM_FWD_DECLARE(MessageType);
GPB_ENUM_FWD_DECLARE(MuteState);
GPB_ENUM_FWD_DECLARE(Operation);
GPB_ENUM_FWD_DECLARE(RelieveAstate);
GPB_ENUM_FWD_DECLARE(SharingType);
GPB_ENUM_FWD_DECLARE(TerminalType);
GPB_ENUM_FWD_DECLARE(WebinarState);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - RoomServerRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface RoomServerRoot : GPBRootObject
@end

#pragma mark - EnterRoomRequest

typedef GPB_ENUM(EnterRoomRequest_FieldNumber) {
  EnterRoomRequest_FieldNumber_Token = 1,
  EnterRoomRequest_FieldNumber_Room = 2,
  EnterRoomRequest_FieldNumber_Account = 3,
};

/**
 * 进入房间
 **/
GPB_FINAL @interface EnterRoomRequest : GPBMessage

/** 授权码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;
/** Test to see if @c token has been set. */
@property(nonatomic, readwrite) BOOL hasToken;

/** 房间信息 */
@property(nonatomic, readwrite, strong, null_resettable) Room *room;
/** Test to see if @c room has been set. */
@property(nonatomic, readwrite) BOOL hasRoom;

/** 帐号信息 */
@property(nonatomic, readwrite, strong, null_resettable) Account *account;
/** Test to see if @c account has been set. */
@property(nonatomic, readwrite) BOOL hasAccount;

@end

#pragma mark - EnterRoomResponse

typedef GPB_ENUM(EnterRoomResponse_FieldNumber) {
  EnterRoomResponse_FieldNumber_Room = 1,
  EnterRoomResponse_FieldNumber_Me = 2,
  EnterRoomResponse_FieldNumber_MembersArray = 3,
};

GPB_FINAL @interface EnterRoomResponse : GPBMessage

/** 当前房间状态 */
@property(nonatomic, readwrite, strong, null_resettable) Room *room;
/** Test to see if @c room has been set. */
@property(nonatomic, readwrite) BOOL hasRoom;

/** 当前我需要同步的帐号信息 */
@property(nonatomic, readwrite, strong, null_resettable) Account *me;
/** Test to see if @c me has been set. */
@property(nonatomic, readwrite) BOOL hasMe;

/** 部分成员信息（如共享时的共享人） */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Account*> *membersArray;
/** The number of items in @c membersArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger membersArray_Count;

@end

#pragma mark - ExitRoomRequest

typedef GPB_ENUM(ExitRoomRequest_FieldNumber) {
  ExitRoomRequest_FieldNumber_Token = 1,
  ExitRoomRequest_FieldNumber_AccountId = 2,
  ExitRoomRequest_FieldNumber_RoomId = 3,
  ExitRoomRequest_FieldNumber_MsgId = 4,
};

/**
 * 退出房间
 **/
GPB_FINAL @interface ExitRoomRequest : GPBMessage

/** 授权码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;
/** Test to see if @c token has been set. */
@property(nonatomic, readwrite) BOOL hasToken;

/** 帐号ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountId;
/** Test to see if @c accountId has been set. */
@property(nonatomic, readwrite) BOOL hasAccountId;

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

/** 消息ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;
/** Test to see if @c msgId has been set. */
@property(nonatomic, readwrite) BOOL hasMsgId;

@end

#pragma mark - HeartbeatRequest

typedef GPB_ENUM(HeartbeatRequest_FieldNumber) {
  HeartbeatRequest_FieldNumber_Token = 1,
  HeartbeatRequest_FieldNumber_RoomId = 2,
  HeartbeatRequest_FieldNumber_Account = 3,
};

/**
 * 心跳
 **/
GPB_FINAL @interface HeartbeatRequest : GPBMessage

/** 授权码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;
/** Test to see if @c token has been set. */
@property(nonatomic, readwrite) BOOL hasToken;

/** ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

/** 帐号信息 */
@property(nonatomic, readwrite, strong, null_resettable) Account *account;
/** Test to see if @c account has been set. */
@property(nonatomic, readwrite) BOOL hasAccount;

@end

#pragma mark - HostCtrlRequest

typedef GPB_ENUM(HostCtrlRequest_FieldNumber) {
  HostCtrlRequest_FieldNumber_Token = 1,
  HostCtrlRequest_FieldNumber_AccountId = 2,
  HostCtrlRequest_FieldNumber_RoomId = 3,
  HostCtrlRequest_FieldNumber_TargetId = 4,
  HostCtrlRequest_FieldNumber_VideoState = 5,
  HostCtrlRequest_FieldNumber_AudioState = 6,
};

/**
 * 主持人禁用音视频
 **/
GPB_FINAL @interface HostCtrlRequest : GPBMessage

/** 授权码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;
/** Test to see if @c token has been set. */
@property(nonatomic, readwrite) BOOL hasToken;

/** 主持人ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountId;
/** Test to see if @c accountId has been set. */
@property(nonatomic, readwrite) BOOL hasAccountId;

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

/** 目标帐号ID,空表示全局禁用 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;
/** Test to see if @c targetId has been set. */
@property(nonatomic, readwrite) BOOL hasTargetId;

/** 视频状态 */
@property(nonatomic, readwrite) enum DeviceState videoState;

@property(nonatomic, readwrite) BOOL hasVideoState;
/** 音频状态 */
@property(nonatomic, readwrite) enum DeviceState audioState;

@property(nonatomic, readwrite) BOOL hasAudioState;
@end

#pragma mark - HostKickoutRequest

typedef GPB_ENUM(HostKickoutRequest_FieldNumber) {
  HostKickoutRequest_FieldNumber_Token = 1,
  HostKickoutRequest_FieldNumber_AccountId = 2,
  HostKickoutRequest_FieldNumber_RoomId = 3,
  HostKickoutRequest_FieldNumber_TargetId = 4,
};

/**
 * 主持人踢人
 **/
GPB_FINAL @interface HostKickoutRequest : GPBMessage

/** 授权码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;
/** Test to see if @c token has been set. */
@property(nonatomic, readwrite) BOOL hasToken;

/** 主持人ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountId;
/** Test to see if @c accountId has been set. */
@property(nonatomic, readwrite) BOOL hasAccountId;

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

/** 目标帐号ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;
/** Test to see if @c targetId has been set. */
@property(nonatomic, readwrite) BOOL hasTargetId;

@end

#pragma mark - HostWhiteBoardRequest

typedef GPB_ENUM(HostWhiteBoardRequest_FieldNumber) {
  HostWhiteBoardRequest_FieldNumber_Token = 1,
  HostWhiteBoardRequest_FieldNumber_AccountId = 2,
  HostWhiteBoardRequest_FieldNumber_RoomId = 3,
  HostWhiteBoardRequest_FieldNumber_IsOpen = 4,
};

/**
 * 主持人打开关闭电子白板[已废弃]
 **/
GPB_FINAL @interface HostWhiteBoardRequest : GPBMessage

/** 授权码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;
/** Test to see if @c token has been set. */
@property(nonatomic, readwrite) BOOL hasToken;

/** 主持人ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountId;
/** Test to see if @c accountId has been set. */
@property(nonatomic, readwrite) BOOL hasAccountId;

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

/** 是否打开 */
@property(nonatomic, readwrite) BOOL isOpen;

@property(nonatomic, readwrite) BOOL hasIsOpen;
@end

#pragma mark - StartToShareRequest

typedef GPB_ENUM(StartToShareRequest_FieldNumber) {
  StartToShareRequest_FieldNumber_Token = 1,
  StartToShareRequest_FieldNumber_AccountId = 2,
  StartToShareRequest_FieldNumber_RoomId = 3,
  StartToShareRequest_FieldNumber_SharingType = 4,
  StartToShareRequest_FieldNumber_SharingPicURL = 5,
  StartToShareRequest_FieldNumber_SharingStreamId = 6,
  StartToShareRequest_FieldNumber_SharingRelativePicURL = 7,
};

/**
 * 开始分享
 **/
GPB_FINAL @interface StartToShareRequest : GPBMessage

/** 授权码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;
/** Test to see if @c token has been set. */
@property(nonatomic, readwrite) BOOL hasToken;

/** 分享者ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountId;
/** Test to see if @c accountId has been set. */
@property(nonatomic, readwrite) BOOL hasAccountId;

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

/** 1-电子白板;2-图片;3-桌面窗口 */
@property(nonatomic, readwrite) enum SharingType sharingType;

@property(nonatomic, readwrite) BOOL hasSharingType;
/** 分享图片时的图片地址 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sharingPicURL;
/** Test to see if @c sharingPicURL has been set. */
@property(nonatomic, readwrite) BOOL hasSharingPicURL;

/** 分享屏幕时的码流ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sharingStreamId;
/** Test to see if @c sharingStreamId has been set. */
@property(nonatomic, readwrite) BOOL hasSharingStreamId;

/** 分享图片时的图片相对地址 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sharingRelativePicURL;
/** Test to see if @c sharingRelativePicURL has been set. */
@property(nonatomic, readwrite) BOOL hasSharingRelativePicURL;

@end

#pragma mark - StopSharingRequest

typedef GPB_ENUM(StopSharingRequest_FieldNumber) {
  StopSharingRequest_FieldNumber_Token = 1,
  StopSharingRequest_FieldNumber_AccountId = 2,
  StopSharingRequest_FieldNumber_RoomId = 3,
};

/**
 * 停止分享
 **/
GPB_FINAL @interface StopSharingRequest : GPBMessage

/** 授权码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;
/** Test to see if @c token has been set. */
@property(nonatomic, readwrite) BOOL hasToken;

/** 分享者ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountId;
/** Test to see if @c accountId has been set. */
@property(nonatomic, readwrite) BOOL hasAccountId;

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

@end

#pragma mark - AdminCtrlRequest

typedef GPB_ENUM(AdminCtrlRequest_FieldNumber) {
  AdminCtrlRequest_FieldNumber_Token = 1,
  AdminCtrlRequest_FieldNumber_RoomId = 2,
  AdminCtrlRequest_FieldNumber_TargetId = 3,
  AdminCtrlRequest_FieldNumber_VideoState = 4,
  AdminCtrlRequest_FieldNumber_AudioState = 5,
};

/**
 * 后台禁用音视频
 **/
GPB_FINAL @interface AdminCtrlRequest : GPBMessage

/** 授权码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;
/** Test to see if @c token has been set. */
@property(nonatomic, readwrite) BOOL hasToken;

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

/** 目标帐号ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;
/** Test to see if @c targetId has been set. */
@property(nonatomic, readwrite) BOOL hasTargetId;

/** 视频状态 */
@property(nonatomic, readwrite) enum DeviceState videoState;

@property(nonatomic, readwrite) BOOL hasVideoState;
/** 音频状态 */
@property(nonatomic, readwrite) enum DeviceState audioState;

@property(nonatomic, readwrite) BOOL hasAudioState;
@end

#pragma mark - AdminKickoutRequest

typedef GPB_ENUM(AdminKickoutRequest_FieldNumber) {
  AdminKickoutRequest_FieldNumber_Token = 1,
  AdminKickoutRequest_FieldNumber_RoomId = 2,
  AdminKickoutRequest_FieldNumber_TargetId = 3,
};

/**
 * 后台踢人
 **/
GPB_FINAL @interface AdminKickoutRequest : GPBMessage

/** 授权码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;
/** Test to see if @c token has been set. */
@property(nonatomic, readwrite) BOOL hasToken;

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

/** 目标帐号ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;
/** Test to see if @c targetId has been set. */
@property(nonatomic, readwrite) BOOL hasTargetId;

@end

#pragma mark - AdminBeginRequest

typedef GPB_ENUM(AdminBeginRequest_FieldNumber) {
  AdminBeginRequest_FieldNumber_Token = 1,
  AdminBeginRequest_FieldNumber_RoomId = 2,
};

/**
 * 后台开始会议
 **/
GPB_FINAL @interface AdminBeginRequest : GPBMessage

/** 授权码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;
/** Test to see if @c token has been set. */
@property(nonatomic, readwrite) BOOL hasToken;

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

@end

#pragma mark - AdminEndRequest

typedef GPB_ENUM(AdminEndRequest_FieldNumber) {
  AdminEndRequest_FieldNumber_Token = 1,
  AdminEndRequest_FieldNumber_RoomId = 2,
};

/**
 * 后台结束会议
 **/
GPB_FINAL @interface AdminEndRequest : GPBMessage

/** 授权码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;
/** Test to see if @c token has been set. */
@property(nonatomic, readwrite) BOOL hasToken;

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

@end

#pragma mark - StreamChangedRequest

typedef GPB_ENUM(StreamChangedRequest_FieldNumber) {
  StreamChangedRequest_FieldNumber_Token = 1,
  StreamChangedRequest_FieldNumber_AccountId = 2,
  StreamChangedRequest_FieldNumber_RoomId = 3,
  StreamChangedRequest_FieldNumber_Operation = 4,
  StreamChangedRequest_FieldNumber_Stream = 5,
};

/**
 * 码流变化
 **/
GPB_FINAL @interface StreamChangedRequest : GPBMessage

/** 授权码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;
/** Test to see if @c token has been set. */
@property(nonatomic, readwrite) BOOL hasToken;

/** 帐号ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountId;
/** Test to see if @c accountId has been set. */
@property(nonatomic, readwrite) BOOL hasAccountId;

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

/** 0-关闭;1-打开;2-修改 */
@property(nonatomic, readwrite) enum Operation operation;

@property(nonatomic, readwrite) BOOL hasOperation;
/** 码流信息 */
@property(nonatomic, readwrite, strong, null_resettable) Stream *stream;
/** Test to see if @c stream has been set. */
@property(nonatomic, readwrite) BOOL hasStream;

@end

#pragma mark - StreamNotify

typedef GPB_ENUM(StreamNotify_FieldNumber) {
  StreamNotify_FieldNumber_AccountId = 1,
  StreamNotify_FieldNumber_SdkNo = 2,
  StreamNotify_FieldNumber_Operation = 3,
  StreamNotify_FieldNumber_Stream = 4,
};

/**
 * 码流变化通知
 **/
GPB_FINAL @interface StreamNotify : GPBMessage

/** 帐号ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountId;
/** Test to see if @c accountId has been set. */
@property(nonatomic, readwrite) BOOL hasAccountId;

/** 帐号SdkNo */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sdkNo;
/** Test to see if @c sdkNo has been set. */
@property(nonatomic, readwrite) BOOL hasSdkNo;

/** 0-关闭;1-打开;2-修改 */
@property(nonatomic, readwrite) enum Operation operation;

@property(nonatomic, readwrite) BOOL hasOperation;
/** 码流信息 */
@property(nonatomic, readwrite, strong, null_resettable) Stream *stream;
/** Test to see if @c stream has been set. */
@property(nonatomic, readwrite) BOOL hasStream;

@end

#pragma mark - PassthroughRequest

typedef GPB_ENUM(PassthroughRequest_FieldNumber) {
  PassthroughRequest_FieldNumber_AccountId = 1,
  PassthroughRequest_FieldNumber_RoomId = 2,
  PassthroughRequest_FieldNumber_TargetId = 3,
  PassthroughRequest_FieldNumber_Message = 4,
};

/**
 * 透传
 **/
GPB_FINAL @interface PassthroughRequest : GPBMessage

/** 发起者帐号ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountId;
/** Test to see if @c accountId has been set. */
@property(nonatomic, readwrite) BOOL hasAccountId;

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

/** 目标帐号ID，NULL表示发向全部 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;
/** Test to see if @c targetId has been set. */
@property(nonatomic, readwrite) BOOL hasTargetId;

/** 透传数据 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *message;
/** Test to see if @c message has been set. */
@property(nonatomic, readwrite) BOOL hasMessage;

@end

#pragma mark - PassthroughNotify

typedef GPB_ENUM(PassthroughNotify_FieldNumber) {
  PassthroughNotify_FieldNumber_AccountId = 1,
  PassthroughNotify_FieldNumber_RoomId = 2,
  PassthroughNotify_FieldNumber_TargetId = 3,
  PassthroughNotify_FieldNumber_Message = 4,
};

/**
 * 透传通知
 **/
GPB_FINAL @interface PassthroughNotify : GPBMessage

/** 帐号ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountId;
/** Test to see if @c accountId has been set. */
@property(nonatomic, readwrite) BOOL hasAccountId;

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

/** 目标帐号ID，NULL表示发向全部 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;
/** Test to see if @c targetId has been set. */
@property(nonatomic, readwrite) BOOL hasTargetId;

/** 透传数据 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *message;
/** Test to see if @c message has been set. */
@property(nonatomic, readwrite) BOOL hasMessage;

@end

#pragma mark - HostCtrlStreamRequest

typedef GPB_ENUM(HostCtrlStreamRequest_FieldNumber) {
  HostCtrlStreamRequest_FieldNumber_Token = 1,
  HostCtrlStreamRequest_FieldNumber_AccountId = 2,
  HostCtrlStreamRequest_FieldNumber_RoomId = 3,
  HostCtrlStreamRequest_FieldNumber_TargetId = 4,
  HostCtrlStreamRequest_FieldNumber_Operation = 5,
  HostCtrlStreamRequest_FieldNumber_Stream = 6,
};

/**
 * 主持人操作码流
 **/
GPB_FINAL @interface HostCtrlStreamRequest : GPBMessage

/** 授权码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;
/** Test to see if @c token has been set. */
@property(nonatomic, readwrite) BOOL hasToken;

/** 帐号ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountId;
/** Test to see if @c accountId has been set. */
@property(nonatomic, readwrite) BOOL hasAccountId;

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

/** 目标帐号ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;
/** Test to see if @c targetId has been set. */
@property(nonatomic, readwrite) BOOL hasTargetId;

/** 码流操作 */
@property(nonatomic, readwrite) enum Operation operation;

@property(nonatomic, readwrite) BOOL hasOperation;
/** 码流信息 */
@property(nonatomic, readwrite, strong, null_resettable) Stream *stream;
/** Test to see if @c stream has been set. */
@property(nonatomic, readwrite) BOOL hasStream;

@end

#pragma mark - HostCtrlStreamNotify

typedef GPB_ENUM(HostCtrlStreamNotify_FieldNumber) {
  HostCtrlStreamNotify_FieldNumber_AccountId = 1,
  HostCtrlStreamNotify_FieldNumber_RoomId = 2,
  HostCtrlStreamNotify_FieldNumber_TargetId = 3,
  HostCtrlStreamNotify_FieldNumber_SdkNo = 4,
  HostCtrlStreamNotify_FieldNumber_Operation = 5,
  HostCtrlStreamNotify_FieldNumber_Stream = 6,
};

/**
 * 主持人操作码流通知
 **/
GPB_FINAL @interface HostCtrlStreamNotify : GPBMessage

/** 帐号ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountId;
/** Test to see if @c accountId has been set. */
@property(nonatomic, readwrite) BOOL hasAccountId;

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

/** 目标帐号ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;
/** Test to see if @c targetId has been set. */
@property(nonatomic, readwrite) BOOL hasTargetId;

/** 目标帐号SdkNo */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sdkNo;
/** Test to see if @c sdkNo has been set. */
@property(nonatomic, readwrite) BOOL hasSdkNo;

/** 码流操作 */
@property(nonatomic, readwrite) enum Operation operation;

@property(nonatomic, readwrite) BOOL hasOperation;
/** 码流信息 */
@property(nonatomic, readwrite, strong, null_resettable) Stream *stream;
/** Test to see if @c stream has been set. */
@property(nonatomic, readwrite) BOOL hasStream;

@end

#pragma mark - RoomNotify

typedef GPB_ENUM(RoomNotify_FieldNumber) {
  RoomNotify_FieldNumber_Room = 1,
};

/**
 * 会议室状态通知
 **/
GPB_FINAL @interface RoomNotify : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Room *room;
/** Test to see if @c room has been set. */
@property(nonatomic, readwrite) BOOL hasRoom;

@end

#pragma mark - AccountNotify

typedef GPB_ENUM(AccountNotify_FieldNumber) {
  AccountNotify_FieldNumber_Account = 1,
  AccountNotify_FieldNumber_RoomId = 2,
  AccountNotify_FieldNumber_RoomNo = 3,
  AccountNotify_FieldNumber_RoomSdkno = 4,
};

/**
 * 成员状态通知
 **/
GPB_FINAL @interface AccountNotify : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Account *account;
/** Test to see if @c account has been set. */
@property(nonatomic, readwrite) BOOL hasAccount;

@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *roomNo;
/** Test to see if @c roomNo has been set. */
@property(nonatomic, readwrite) BOOL hasRoomNo;

@property(nonatomic, readwrite, copy, null_resettable) NSString *roomSdkno;
/** Test to see if @c roomSdkno has been set. */
@property(nonatomic, readwrite) BOOL hasRoomSdkno;

@end

#pragma mark - MyAccountNotify

typedef GPB_ENUM(MyAccountNotify_FieldNumber) {
  MyAccountNotify_FieldNumber_Account = 1,
};

/**
 * 我的状态变化通知
 **/
GPB_FINAL @interface MyAccountNotify : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Account *account;
/** Test to see if @c account has been set. */
@property(nonatomic, readwrite) BOOL hasAccount;

@end

#pragma mark - KickoutNotify

typedef GPB_ENUM(KickoutNotify_FieldNumber) {
  KickoutNotify_FieldNumber_AccountId = 1,
  KickoutNotify_FieldNumber_AccountTokenId = 2,
  KickoutNotify_FieldNumber_Msg = 3,
};

/**
 * 被踢通知
 **/
GPB_FINAL @interface KickoutNotify : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *accountId;
/** Test to see if @c accountId has been set. */
@property(nonatomic, readwrite) BOOL hasAccountId;

/** 被踢的用户token_id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountTokenId;
/** Test to see if @c accountTokenId has been set. */
@property(nonatomic, readwrite) BOOL hasAccountTokenId;

/** 推送消息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

@end

#pragma mark - EnterNotify

typedef GPB_ENUM(EnterNotify_FieldNumber) {
  EnterNotify_FieldNumber_Account = 1,
  EnterNotify_FieldNumber_RoomId = 2,
  EnterNotify_FieldNumber_RoomNo = 3,
  EnterNotify_FieldNumber_RoomSdkno = 4,
  EnterNotify_FieldNumber_MsgId = 5,
};

/**
 * 成员进入通知
 **/
GPB_FINAL @interface EnterNotify : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Account *account;
/** Test to see if @c account has been set. */
@property(nonatomic, readwrite) BOOL hasAccount;

@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *roomNo;
/** Test to see if @c roomNo has been set. */
@property(nonatomic, readwrite) BOOL hasRoomNo;

@property(nonatomic, readwrite, copy, null_resettable) NSString *roomSdkno;
/** Test to see if @c roomSdkno has been set. */
@property(nonatomic, readwrite) BOOL hasRoomSdkno;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;
/** Test to see if @c msgId has been set. */
@property(nonatomic, readwrite) BOOL hasMsgId;

@end

#pragma mark - ExitNotify

typedef GPB_ENUM(ExitNotify_FieldNumber) {
  ExitNotify_FieldNumber_Account = 1,
  ExitNotify_FieldNumber_RoomId = 2,
  ExitNotify_FieldNumber_RoomNo = 3,
  ExitNotify_FieldNumber_RoomSdkno = 4,
};

/**
 * 成员退出通知
 **/
GPB_FINAL @interface ExitNotify : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Account *account;
/** Test to see if @c account has been set. */
@property(nonatomic, readwrite) BOOL hasAccount;

@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *roomNo;
/** Test to see if @c roomNo has been set. */
@property(nonatomic, readwrite) BOOL hasRoomNo;

@property(nonatomic, readwrite, copy, null_resettable) NSString *roomSdkno;
/** Test to see if @c roomSdkno has been set. */
@property(nonatomic, readwrite) BOOL hasRoomSdkno;

@end

#pragma mark - RoomBeginNotify

typedef GPB_ENUM(RoomBeginNotify_FieldNumber) {
  RoomBeginNotify_FieldNumber_RoomId = 1,
  RoomBeginNotify_FieldNumber_RoomNo = 2,
  RoomBeginNotify_FieldNumber_ConfId = 3,
};

/**
 * 会议开始通知
 **/
GPB_FINAL @interface RoomBeginNotify : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *roomNo;
/** Test to see if @c roomNo has been set. */
@property(nonatomic, readwrite) BOOL hasRoomNo;

@property(nonatomic, readwrite, copy, null_resettable) NSString *confId;
/** Test to see if @c confId has been set. */
@property(nonatomic, readwrite) BOOL hasConfId;

@end

#pragma mark - RoomEndedNotify

typedef GPB_ENUM(RoomEndedNotify_FieldNumber) {
  RoomEndedNotify_FieldNumber_RoomId = 1,
  RoomEndedNotify_FieldNumber_RoomNo = 2,
  RoomEndedNotify_FieldNumber_ConfId = 3,
};

/**
 * 会议结束通知
 **/
GPB_FINAL @interface RoomEndedNotify : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *roomNo;
/** Test to see if @c roomNo has been set. */
@property(nonatomic, readwrite) BOOL hasRoomNo;

@property(nonatomic, readwrite, copy, null_resettable) NSString *confId;
/** Test to see if @c confId has been set. */
@property(nonatomic, readwrite) BOOL hasConfId;

@end

#pragma mark - RoomPrepareNotify

typedef GPB_ENUM(RoomPrepareNotify_FieldNumber) {
  RoomPrepareNotify_FieldNumber_RoomId = 1,
  RoomPrepareNotify_FieldNumber_RoomNo = 2,
  RoomPrepareNotify_FieldNumber_ConfId = 3,
};

/**
 * 会议预约通知
 **/
GPB_FINAL @interface RoomPrepareNotify : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *roomNo;
/** Test to see if @c roomNo has been set. */
@property(nonatomic, readwrite) BOOL hasRoomNo;

@property(nonatomic, readwrite, copy, null_resettable) NSString *confId;
/** Test to see if @c confId has been set. */
@property(nonatomic, readwrite) BOOL hasConfId;

@end

#pragma mark - RoomChangeNotify

typedef GPB_ENUM(RoomChangeNotify_FieldNumber) {
  RoomChangeNotify_FieldNumber_RoomId = 1,
  RoomChangeNotify_FieldNumber_RoomNo = 2,
  RoomChangeNotify_FieldNumber_ConfId = 3,
};

/**
 * 会议更改通知
 **/
GPB_FINAL @interface RoomChangeNotify : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *roomNo;
/** Test to see if @c roomNo has been set. */
@property(nonatomic, readwrite) BOOL hasRoomNo;

@property(nonatomic, readwrite, copy, null_resettable) NSString *confId;
/** Test to see if @c confId has been set. */
@property(nonatomic, readwrite) BOOL hasConfId;

@end

#pragma mark - AdminWndLayoutRequest

typedef GPB_ENUM(AdminWndLayoutRequest_FieldNumber) {
  AdminWndLayoutRequest_FieldNumber_RoomId = 1,
  AdminWndLayoutRequest_FieldNumber_TargetId = 2,
  AdminWndLayoutRequest_FieldNumber_WndLayout = 3,
};

/**
 * 后台控制布局
 **/
GPB_FINAL @interface AdminWndLayoutRequest : GPBMessage

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

/** 目标帐号ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;
/** Test to see if @c targetId has been set. */
@property(nonatomic, readwrite) BOOL hasTargetId;

/** 布局信息 */
@property(nonatomic, readwrite, strong, null_resettable) WndLayout *wndLayout;
/** Test to see if @c wndLayout has been set. */
@property(nonatomic, readwrite) BOOL hasWndLayout;

@end

#pragma mark - AdminWndLayoutNotify

typedef GPB_ENUM(AdminWndLayoutNotify_FieldNumber) {
  AdminWndLayoutNotify_FieldNumber_RoomId = 1,
  AdminWndLayoutNotify_FieldNumber_TargetId = 2,
  AdminWndLayoutNotify_FieldNumber_SdkNo = 3,
  AdminWndLayoutNotify_FieldNumber_WndLayout = 4,
};

/**
 * 后台控制布局通知
 **/
GPB_FINAL @interface AdminWndLayoutNotify : GPBMessage

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

/** 目标帐号ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;
/** Test to see if @c targetId has been set. */
@property(nonatomic, readwrite) BOOL hasTargetId;

/** 目标帐号SdkNo */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sdkNo;
/** Test to see if @c sdkNo has been set. */
@property(nonatomic, readwrite) BOOL hasSdkNo;

/** 布局信息 */
@property(nonatomic, readwrite, strong, null_resettable) WndLayout *wndLayout;
/** Test to see if @c wndLayout has been set. */
@property(nonatomic, readwrite) BOOL hasWndLayout;

@end

#pragma mark - ChatRequest

typedef GPB_ENUM(ChatRequest_FieldNumber) {
  ChatRequest_FieldNumber_Token = 1,
  ChatRequest_FieldNumber_RoomId = 2,
  ChatRequest_FieldNumber_AccountId = 3,
  ChatRequest_FieldNumber_AccountName = 4,
  ChatRequest_FieldNumber_AccountPortrait = 5,
  ChatRequest_FieldNumber_TargetId = 6,
  ChatRequest_FieldNumber_Type = 7,
  ChatRequest_FieldNumber_Message = 8,
  ChatRequest_FieldNumber_AccountRelativePortrait = 9,
};

/**
 * 发送聊天
 **/
GPB_FINAL @interface ChatRequest : GPBMessage

/** 授权码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;
/** Test to see if @c token has been set. */
@property(nonatomic, readwrite) BOOL hasToken;

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

/** 发送者 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountId;
/** Test to see if @c accountId has been set. */
@property(nonatomic, readwrite) BOOL hasAccountId;

/** 发送者名字 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountName;
/** Test to see if @c accountName has been set. */
@property(nonatomic, readwrite) BOOL hasAccountName;

/** 发送者头像 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountPortrait;
/** Test to see if @c accountPortrait has been set. */
@property(nonatomic, readwrite) BOOL hasAccountPortrait;

/** 发送者头像相对地址 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountRelativePortrait;
/** Test to see if @c accountRelativePortrait has been set. */
@property(nonatomic, readwrite) BOOL hasAccountRelativePortrait;

/** 目标帐号ID, 空则表示发给房间里的所有人 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;
/** Test to see if @c targetId has been set. */
@property(nonatomic, readwrite) BOOL hasTargetId;

/** 消息类型 */
@property(nonatomic, readwrite) enum MessageType type;

@property(nonatomic, readwrite) BOOL hasType;
/** 消息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *message;
/** Test to see if @c message has been set. */
@property(nonatomic, readwrite) BOOL hasMessage;

@end

#pragma mark - ChatNotify

typedef GPB_ENUM(ChatNotify_FieldNumber) {
  ChatNotify_FieldNumber_RoomId = 1,
  ChatNotify_FieldNumber_AccountId = 2,
  ChatNotify_FieldNumber_AccountName = 3,
  ChatNotify_FieldNumber_AccountPortrait = 4,
  ChatNotify_FieldNumber_TargetId = 5,
  ChatNotify_FieldNumber_Type = 6,
  ChatNotify_FieldNumber_Message = 7,
  ChatNotify_FieldNumber_AccountRole = 8,
  ChatNotify_FieldNumber_AccountChatState = 9,
  ChatNotify_FieldNumber_TerminalType = 10,
  ChatNotify_FieldNumber_AccountRelativePortrait = 11,
};

/**
 * 聊天消息
 **/
GPB_FINAL @interface ChatNotify : GPBMessage

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

/** 发送者 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountId;
/** Test to see if @c accountId has been set. */
@property(nonatomic, readwrite) BOOL hasAccountId;

/** 发送者名字 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountName;
/** Test to see if @c accountName has been set. */
@property(nonatomic, readwrite) BOOL hasAccountName;

/** 发送者头像 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountPortrait;
/** Test to see if @c accountPortrait has been set. */
@property(nonatomic, readwrite) BOOL hasAccountPortrait;

/** 发送者角色 */
@property(nonatomic, readwrite) enum ConferenceRole accountRole;

@property(nonatomic, readwrite) BOOL hasAccountRole;
/** 发送者聊天状态 */
@property(nonatomic, readwrite) enum DeviceState accountChatState;

@property(nonatomic, readwrite) BOOL hasAccountChatState;
/** 发送者终端类型 */
@property(nonatomic, readwrite) enum TerminalType terminalType;

@property(nonatomic, readwrite) BOOL hasTerminalType;
/** 发送者头像相对地址 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountRelativePortrait;
/** Test to see if @c accountRelativePortrait has been set. */
@property(nonatomic, readwrite) BOOL hasAccountRelativePortrait;

/** 目标帐号ID, 空则表示发给房间里的所有人 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;
/** Test to see if @c targetId has been set. */
@property(nonatomic, readwrite) BOOL hasTargetId;

/** 消息类型 */
@property(nonatomic, readwrite) enum MessageType type;

@property(nonatomic, readwrite) BOOL hasType;
/** 消息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *message;
/** Test to see if @c message has been set. */
@property(nonatomic, readwrite) BOOL hasMessage;

@end

#pragma mark - SetWaterMark

typedef GPB_ENUM(SetWaterMark_FieldNumber) {
  SetWaterMark_FieldNumber_Token = 1,
  SetWaterMark_FieldNumber_RoomId = 2,
  SetWaterMark_FieldNumber_AccountId = 3,
  SetWaterMark_FieldNumber_Watermark = 4,
};

GPB_FINAL @interface SetWaterMark : GPBMessage

/** 授权码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;
/** Test to see if @c token has been set. */
@property(nonatomic, readwrite) BOOL hasToken;

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

/** 发送者 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountId;
/** Test to see if @c accountId has been set. */
@property(nonatomic, readwrite) BOOL hasAccountId;

/** 是否开启水印 */
@property(nonatomic, readwrite) BOOL watermark;

@property(nonatomic, readwrite) BOOL hasWatermark;
@end

#pragma mark - HandUpRequest

typedef GPB_ENUM(HandUpRequest_FieldNumber) {
  HandUpRequest_FieldNumber_Token = 1,
  HandUpRequest_FieldNumber_RoomId = 2,
  HandUpRequest_FieldNumber_AccountId = 3,
  HandUpRequest_FieldNumber_TargetId = 4,
  HandUpRequest_FieldNumber_Hus = 5,
  HandUpRequest_FieldNumber_Result = 6,
  HandUpRequest_FieldNumber_Role = 7,
};

GPB_FINAL @interface HandUpRequest : GPBMessage

/** 授权码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;
/** Test to see if @c token has been set. */
@property(nonatomic, readwrite) BOOL hasToken;

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

/** 发送者 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountId;
/** Test to see if @c accountId has been set. */
@property(nonatomic, readwrite) BOOL hasAccountId;

/** 处理人 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;
/** Test to see if @c targetId has been set. */
@property(nonatomic, readwrite) BOOL hasTargetId;

/** 举手 */
@property(nonatomic, readwrite) enum HandUpStatus hus;

@property(nonatomic, readwrite) BOOL hasHus;
/** 处理结果    0-同意；其他 */
@property(nonatomic, readwrite) int32_t result;

@property(nonatomic, readwrite) BOOL hasResult;
/** 0:嘉宾; 1:观众 */
@property(nonatomic, readwrite) int32_t role;

@property(nonatomic, readwrite) BOOL hasRole;
@end

#pragma mark - HandUpNotify

typedef GPB_ENUM(HandUpNotify_FieldNumber) {
  HandUpNotify_FieldNumber_RoomId = 1,
  HandUpNotify_FieldNumber_AccountId = 2,
  HandUpNotify_FieldNumber_AccountName = 3,
  HandUpNotify_FieldNumber_Hus = 4,
  HandUpNotify_FieldNumber_Result = 5,
  HandUpNotify_FieldNumber_Role = 6,
};

GPB_FINAL @interface HandUpNotify : GPBMessage

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

/** 主持人ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountId;
/** Test to see if @c accountId has been set. */
@property(nonatomic, readwrite) BOOL hasAccountId;

/** 主持人名字 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountName;
/** Test to see if @c accountName has been set. */
@property(nonatomic, readwrite) BOOL hasAccountName;

/** 举手 */
@property(nonatomic, readwrite) enum HandUpStatus hus;

@property(nonatomic, readwrite) BOOL hasHus;
/** 处理结果    0-同意；其他 */
@property(nonatomic, readwrite) int32_t result;

@property(nonatomic, readwrite) BOOL hasResult;
/** 0:嘉宾; 1:观众 */
@property(nonatomic, readwrite) int32_t role;

@property(nonatomic, readwrite) BOOL hasRole;
@end

#pragma mark - SetMemberStateRequest

typedef GPB_ENUM(SetMemberStateRequest_FieldNumber) {
  SetMemberStateRequest_FieldNumber_Token = 1,
  SetMemberStateRequest_FieldNumber_AccountId = 2,
  SetMemberStateRequest_FieldNumber_RoomId = 3,
  SetMemberStateRequest_FieldNumber_TargetidsArray = 4,
  SetMemberStateRequest_FieldNumber_VideoState = 5,
  SetMemberStateRequest_FieldNumber_AudioState = 6,
  SetMemberStateRequest_FieldNumber_ChatState = 7,
};

/**
 * 主持人禁用成员音视频
 **/
GPB_FINAL @interface SetMemberStateRequest : GPBMessage

/** 授权码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;
/** Test to see if @c token has been set. */
@property(nonatomic, readwrite) BOOL hasToken;

/** 主持人ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountId;
/** Test to see if @c accountId has been set. */
@property(nonatomic, readwrite) BOOL hasAccountId;

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

/** 目标帐号ID集合,空表示全局禁用 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *targetidsArray;
/** The number of items in @c targetidsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger targetidsArray_Count;

/** 视频状态 */
@property(nonatomic, readwrite) enum DeviceState videoState;

@property(nonatomic, readwrite) BOOL hasVideoState;
/** 音频状态 */
@property(nonatomic, readwrite) enum DeviceState audioState;

@property(nonatomic, readwrite) BOOL hasAudioState;
/** 聊天状态 */
@property(nonatomic, readwrite) enum DeviceState chatState;

@property(nonatomic, readwrite) BOOL hasChatState;
@end

#pragma mark - SetRoomStateRequest

typedef GPB_ENUM(SetRoomStateRequest_FieldNumber) {
  SetRoomStateRequest_FieldNumber_Token = 1,
  SetRoomStateRequest_FieldNumber_AccountId = 2,
  SetRoomStateRequest_FieldNumber_RoomId = 3,
  SetRoomStateRequest_FieldNumber_Locked = 4,
  SetRoomStateRequest_FieldNumber_VideoState = 5,
  SetRoomStateRequest_FieldNumber_AudioState = 6,
  SetRoomStateRequest_FieldNumber_WebinarChat = 7,
  SetRoomStateRequest_FieldNumber_WebinarScreenShot = 8,
};

/**
 * 主持人禁用房间音视频
 **/
GPB_FINAL @interface SetRoomStateRequest : GPBMessage

/** 授权码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;
/** Test to see if @c token has been set. */
@property(nonatomic, readwrite) BOOL hasToken;

/** 主持人ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountId;
/** Test to see if @c accountId has been set. */
@property(nonatomic, readwrite) BOOL hasAccountId;

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

/** 锁定房间状态 */
@property(nonatomic, readwrite) BOOL locked;

@property(nonatomic, readwrite) BOOL hasLocked;
/** 视频状态 */
@property(nonatomic, readwrite) enum DeviceState videoState;

@property(nonatomic, readwrite) BOOL hasVideoState;
/** 音频状态 */
@property(nonatomic, readwrite) enum DeviceState audioState;

@property(nonatomic, readwrite) BOOL hasAudioState;
/** 聊天状态 */
@property(nonatomic, readwrite) enum WebinarState webinarChat;

@property(nonatomic, readwrite) BOOL hasWebinarChat;
/** 截屏状态 */
@property(nonatomic, readwrite) enum WebinarState webinarScreenShot;

@property(nonatomic, readwrite) BOOL hasWebinarScreenShot;
@end

#pragma mark - SetRoomMoveHostRequest

typedef GPB_ENUM(SetRoomMoveHostRequest_FieldNumber) {
  SetRoomMoveHostRequest_FieldNumber_Token = 1,
  SetRoomMoveHostRequest_FieldNumber_TargetId = 2,
  SetRoomMoveHostRequest_FieldNumber_SourceId = 3,
  SetRoomMoveHostRequest_FieldNumber_RoomId = 4,
  SetRoomMoveHostRequest_FieldNumber_MsgId = 5,
};

/**
 * 转移主持人 dx 1.1.6
 **/
GPB_FINAL @interface SetRoomMoveHostRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;
/** Test to see if @c token has been set. */
@property(nonatomic, readwrite) BOOL hasToken;

/** 目标帐号ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;
/** Test to see if @c targetId has been set. */
@property(nonatomic, readwrite) BOOL hasTargetId;

/** 源账号ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sourceId;
/** Test to see if @c sourceId has been set. */
@property(nonatomic, readwrite) BOOL hasSourceId;

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

/** 消息ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;
/** Test to see if @c msgId has been set. */
@property(nonatomic, readwrite) BOOL hasMsgId;

@end

#pragma mark - RoomMoveHostNotify

typedef GPB_ENUM(RoomMoveHostNotify_FieldNumber) {
  RoomMoveHostNotify_FieldNumber_TargetId = 1,
  RoomMoveHostNotify_FieldNumber_SourceId = 2,
  RoomMoveHostNotify_FieldNumber_RoomId = 3,
  RoomMoveHostNotify_FieldNumber_MsgId = 4,
};

/**
 * 转移主持人通知 dx 1.1.6
 **/
GPB_FINAL @interface RoomMoveHostNotify : GPBMessage

/** 目标帐号ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;
/** Test to see if @c targetId has been set. */
@property(nonatomic, readwrite) BOOL hasTargetId;

/** 源账号ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sourceId;
/** Test to see if @c sourceId has been set. */
@property(nonatomic, readwrite) BOOL hasSourceId;

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

/** 消息ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;
/** Test to see if @c msgId has been set. */
@property(nonatomic, readwrite) BOOL hasMsgId;

@end

#pragma mark - SetRoomUnionHostRequest

typedef GPB_ENUM(SetRoomUnionHostRequest_FieldNumber) {
  SetRoomUnionHostRequest_FieldNumber_Token = 1,
  SetRoomUnionHostRequest_FieldNumber_TargetId = 2,
  SetRoomUnionHostRequest_FieldNumber_SourceId = 3,
  SetRoomUnionHostRequest_FieldNumber_RoomId = 4,
  SetRoomUnionHostRequest_FieldNumber_State = 5,
  SetRoomUnionHostRequest_FieldNumber_MsgId = 6,
};

/**
 * 设置联席主持人 dx 1.1.6
 **/
GPB_FINAL @interface SetRoomUnionHostRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;
/** Test to see if @c token has been set. */
@property(nonatomic, readwrite) BOOL hasToken;

/** 目标帐号ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;
/** Test to see if @c targetId has been set. */
@property(nonatomic, readwrite) BOOL hasTargetId;

/** 源账号ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sourceId;
/** Test to see if @c sourceId has been set. */
@property(nonatomic, readwrite) BOOL hasSourceId;

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

/** 是否状态 */
@property(nonatomic, readwrite) BOOL state;

@property(nonatomic, readwrite) BOOL hasState;
/** 消息ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;
/** Test to see if @c msgId has been set. */
@property(nonatomic, readwrite) BOOL hasMsgId;

@end

#pragma mark - RoomUnionHostNotify

typedef GPB_ENUM(RoomUnionHostNotify_FieldNumber) {
  RoomUnionHostNotify_FieldNumber_TargetId = 1,
  RoomUnionHostNotify_FieldNumber_SourceId = 2,
  RoomUnionHostNotify_FieldNumber_RoomId = 3,
  RoomUnionHostNotify_FieldNumber_State = 4,
};

/**
 * 设置联席主持人通知 dx 1.1.6
 **/
GPB_FINAL @interface RoomUnionHostNotify : GPBMessage

/** 目标帐号ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;
/** Test to see if @c targetId has been set. */
@property(nonatomic, readwrite) BOOL hasTargetId;

/** 源账号ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sourceId;
/** Test to see if @c sourceId has been set. */
@property(nonatomic, readwrite) BOOL hasSourceId;

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

/** 是否状态 */
@property(nonatomic, readwrite) BOOL state;

@property(nonatomic, readwrite) BOOL hasState;
@end

#pragma mark - SetRoomRecoveryHostRequest

typedef GPB_ENUM(SetRoomRecoveryHostRequest_FieldNumber) {
  SetRoomRecoveryHostRequest_FieldNumber_Token = 1,
  SetRoomRecoveryHostRequest_FieldNumber_RoomId = 2,
  SetRoomRecoveryHostRequest_FieldNumber_AccountId = 3,
  SetRoomRecoveryHostRequest_FieldNumber_TargetId = 4,
  SetRoomRecoveryHostRequest_FieldNumber_MsgId = 5,
};

/**
 * 收回主持人 dx 1.1.6
 **/
GPB_FINAL @interface SetRoomRecoveryHostRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;
/** Test to see if @c token has been set. */
@property(nonatomic, readwrite) BOOL hasToken;

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

/** 账号ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountId;
/** Test to see if @c accountId has been set. */
@property(nonatomic, readwrite) BOOL hasAccountId;

/** 目标账号ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;
/** Test to see if @c targetId has been set. */
@property(nonatomic, readwrite) BOOL hasTargetId;

/** 消息ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;
/** Test to see if @c msgId has been set. */
@property(nonatomic, readwrite) BOOL hasMsgId;

@end

#pragma mark - RoomRecoveryHostNotify

typedef GPB_ENUM(RoomRecoveryHostNotify_FieldNumber) {
  RoomRecoveryHostNotify_FieldNumber_RoomId = 1,
  RoomRecoveryHostNotify_FieldNumber_AccountId = 2,
  RoomRecoveryHostNotify_FieldNumber_TargetId = 3,
  RoomRecoveryHostNotify_FieldNumber_MsgId = 4,
};

/**
 * 收回主持人通知 dx 1.1.6
 **/
GPB_FINAL @interface RoomRecoveryHostNotify : GPBMessage

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

/** 账号ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountId;
/** Test to see if @c accountId has been set. */
@property(nonatomic, readwrite) BOOL hasAccountId;

/** 目标账号ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;
/** Test to see if @c targetId has been set. */
@property(nonatomic, readwrite) BOOL hasTargetId;

/** 消息ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;
/** Test to see if @c msgId has been set. */
@property(nonatomic, readwrite) BOOL hasMsgId;

@end

#pragma mark - XChatMessageAttachmemt

typedef GPB_ENUM(XChatMessageAttachmemt_FieldNumber) {
  XChatMessageAttachmemt_FieldNumber_Name = 1,
  XChatMessageAttachmemt_FieldNumber_URL = 2,
  XChatMessageAttachmemt_FieldNumber_Type = 3,
};

/**
 * 聊天消息的附件
 **/
GPB_FINAL @interface XChatMessageAttachmemt : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;
/** Test to see if @c name has been set. */
@property(nonatomic, readwrite) BOOL hasName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;
/** Test to see if @c URL has been set. */
@property(nonatomic, readwrite) BOOL hasURL;

@property(nonatomic, readwrite) enum MessageType type;

@property(nonatomic, readwrite) BOOL hasType;
@end

#pragma mark - XChatMessage

typedef GPB_ENUM(XChatMessage_FieldNumber) {
  XChatMessage_FieldNumber_Id_p = 1,
  XChatMessage_FieldNumber_Content = 2,
  XChatMessage_FieldNumber_AccountId = 3,
  XChatMessage_FieldNumber_AccountName = 4,
  XChatMessage_FieldNumber_AccountNickname = 5,
  XChatMessage_FieldNumber_AccountPortrait = 6,
  XChatMessage_FieldNumber_RootRef = 7,
  XChatMessage_FieldNumber_PrevRef = 8,
  XChatMessage_FieldNumber_CreatedAt = 9,
  XChatMessage_FieldNumber_AttachmentsArray = 10,
};

/**
 * 聊天消息
 **/
GPB_FINAL @interface XChatMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;
/** Test to see if @c id_p has been set. */
@property(nonatomic, readwrite) BOOL hasId_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;
/** Test to see if @c content has been set. */
@property(nonatomic, readwrite) BOOL hasContent;

@property(nonatomic, readwrite, copy, null_resettable) NSString *accountId;
/** Test to see if @c accountId has been set. */
@property(nonatomic, readwrite) BOOL hasAccountId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *accountName;
/** Test to see if @c accountName has been set. */
@property(nonatomic, readwrite) BOOL hasAccountName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *accountNickname;
/** Test to see if @c accountNickname has been set. */
@property(nonatomic, readwrite) BOOL hasAccountNickname;

@property(nonatomic, readwrite, copy, null_resettable) NSString *accountPortrait;
/** Test to see if @c accountPortrait has been set. */
@property(nonatomic, readwrite) BOOL hasAccountPortrait;

@property(nonatomic, readwrite, copy, null_resettable) NSString *rootRef;
/** Test to see if @c rootRef has been set. */
@property(nonatomic, readwrite) BOOL hasRootRef;

@property(nonatomic, readwrite, copy, null_resettable) NSString *prevRef;
/** Test to see if @c prevRef has been set. */
@property(nonatomic, readwrite) BOOL hasPrevRef;

@property(nonatomic, readwrite) int64_t createdAt;

@property(nonatomic, readwrite) BOOL hasCreatedAt;
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<XChatMessageAttachmemt*> *attachmentsArray;
/** The number of items in @c attachmentsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger attachmentsArray_Count;

@end

#pragma mark - XChatEvent

typedef GPB_ENUM(XChatEvent_FieldNumber) {
  XChatEvent_FieldNumber_RoomId = 1,
  XChatEvent_FieldNumber_Message = 2,
  XChatEvent_FieldNumber_SenderId = 3,
  XChatEvent_FieldNumber_ReceiverIdArray = 4,
};

/**
 * 接收聊天消息
 **/
GPB_FINAL @interface XChatEvent : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

@property(nonatomic, readwrite, strong, null_resettable) XChatMessage *message;
/** Test to see if @c message has been set. */
@property(nonatomic, readwrite) BOOL hasMessage;

@property(nonatomic, readwrite, copy, null_resettable) NSString *senderId;
/** Test to see if @c senderId has been set. */
@property(nonatomic, readwrite) BOOL hasSenderId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *receiverIdArray;
/** The number of items in @c receiverIdArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger receiverIdArray_Count;

@end

#pragma mark - SetMemberMuteRequest

typedef GPB_ENUM(SetMemberMuteRequest_FieldNumber) {
  SetMemberMuteRequest_FieldNumber_Token = 1,
  SetMemberMuteRequest_FieldNumber_RoomId = 2,
  SetMemberMuteRequest_FieldNumber_AccountId = 3,
  SetMemberMuteRequest_FieldNumber_Mute = 4,
};

/**
 * /设置6个静音状态
 **/
GPB_FINAL @interface SetMemberMuteRequest : GPBMessage

/** 授权码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;
/** Test to see if @c token has been set. */
@property(nonatomic, readwrite) BOOL hasToken;

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

/** 发送者 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountId;
/** Test to see if @c accountId has been set. */
@property(nonatomic, readwrite) BOOL hasAccountId;

/** 0-关闭  1-开启  2-人员超过6人 */
@property(nonatomic, readwrite) enum MuteState mute;

@property(nonatomic, readwrite) BOOL hasMute;
@end

#pragma mark - SetMemberNameHostRequest

typedef GPB_ENUM(SetMemberNameHostRequest_FieldNumber) {
  SetMemberNameHostRequest_FieldNumber_Token = 1,
  SetMemberNameHostRequest_FieldNumber_RoomId = 2,
  SetMemberNameHostRequest_FieldNumber_AccountId = 3,
  SetMemberNameHostRequest_FieldNumber_TargetId = 4,
  SetMemberNameHostRequest_FieldNumber_TargetNickname = 5,
};

/**
 * 修改成员呢称
 **/
GPB_FINAL @interface SetMemberNameHostRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;
/** Test to see if @c token has been set. */
@property(nonatomic, readwrite) BOOL hasToken;

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

/** 操作账号ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountId;
/** Test to see if @c accountId has been set. */
@property(nonatomic, readwrite) BOOL hasAccountId;

/** 目标账号ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;
/** Test to see if @c targetId has been set. */
@property(nonatomic, readwrite) BOOL hasTargetId;

/** 目标账号呢称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *targetNickname;
/** Test to see if @c targetNickname has been set. */
@property(nonatomic, readwrite) BOOL hasTargetNickname;

@end

#pragma mark - SetRoomRelieveAstateRequest

typedef GPB_ENUM(SetRoomRelieveAstateRequest_FieldNumber) {
  SetRoomRelieveAstateRequest_FieldNumber_Token = 1,
  SetRoomRelieveAstateRequest_FieldNumber_AccountId = 2,
  SetRoomRelieveAstateRequest_FieldNumber_RoomId = 3,
  SetRoomRelieveAstateRequest_FieldNumber_RelieveAstate = 4,
};

/**
 * 修改房间允许自行解除禁音
 **/
GPB_FINAL @interface SetRoomRelieveAstateRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;
/** Test to see if @c token has been set. */
@property(nonatomic, readwrite) BOOL hasToken;

/** 操作账号ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountId;
/** Test to see if @c accountId has been set. */
@property(nonatomic, readwrite) BOOL hasAccountId;

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

/** 0:允许解除禁音 1:不允许解除禁音 */
@property(nonatomic, readwrite) enum RelieveAstate relieveAstate;

@property(nonatomic, readwrite) BOOL hasRelieveAstate;
@end

#pragma mark - GetRoomAccountStatusRequest

typedef GPB_ENUM(GetRoomAccountStatusRequest_FieldNumber) {
  GetRoomAccountStatusRequest_FieldNumber_Token = 1,
  GetRoomAccountStatusRequest_FieldNumber_AccountId = 2,
  GetRoomAccountStatusRequest_FieldNumber_RoomId = 3,
};

/**
 * 触发会议内账号状态回传
 **/
GPB_FINAL @interface GetRoomAccountStatusRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;
/** Test to see if @c token has been set. */
@property(nonatomic, readwrite) BOOL hasToken;

/** 操作账号ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountId;
/** Test to see if @c accountId has been set. */
@property(nonatomic, readwrite) BOOL hasAccountId;

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

@end

#pragma mark - SetHostsRequest

typedef GPB_ENUM(SetHostsRequest_FieldNumber) {
  SetHostsRequest_FieldNumber_Token = 1,
  SetHostsRequest_FieldNumber_RoomId = 2,
  SetHostsRequest_FieldNumber_HostsArray = 3,
};

GPB_FINAL @interface SetHostsRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;
/** Test to see if @c token has been set. */
@property(nonatomic, readwrite) BOOL hasToken;

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

/** 主播ID */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *hostsArray;
/** The number of items in @c hostsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger hostsArray_Count;

@end

#pragma mark - ConfExtendNotify

typedef GPB_ENUM(ConfExtendNotify_FieldNumber) {
  ConfExtendNotify_FieldNumber_ConfId = 1,
  ConfExtendNotify_FieldNumber_RoomNo = 2,
  ConfExtendNotify_FieldNumber_BeginAt = 3,
  ConfExtendNotify_FieldNumber_EndAt = 4,
};

GPB_FINAL @interface ConfExtendNotify : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *confId;
/** Test to see if @c confId has been set. */
@property(nonatomic, readwrite) BOOL hasConfId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *roomNo;
/** Test to see if @c roomNo has been set. */
@property(nonatomic, readwrite) BOOL hasRoomNo;

@property(nonatomic, readwrite) int64_t beginAt;

@property(nonatomic, readwrite) BOOL hasBeginAt;
@property(nonatomic, readwrite) int64_t endAt;

@property(nonatomic, readwrite) BOOL hasEndAt;
@end

#pragma mark - ConfInviteeNotify

typedef GPB_ENUM(ConfInviteeNotify_FieldNumber) {
  ConfInviteeNotify_FieldNumber_RoomNo = 1,
  ConfInviteeNotify_FieldNumber_ConfId = 2,
};

GPB_FINAL @interface ConfInviteeNotify : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *roomNo;
/** Test to see if @c roomNo has been set. */
@property(nonatomic, readwrite) BOOL hasRoomNo;

@property(nonatomic, readwrite, copy, null_resettable) NSString *confId;
/** Test to see if @c confId has been set. */
@property(nonatomic, readwrite) BOOL hasConfId;

@end

#pragma mark - McuStateNotify

typedef GPB_ENUM(McuStateNotify_FieldNumber) {
  McuStateNotify_FieldNumber_RoomNo = 1,
  McuStateNotify_FieldNumber_McuMode = 2,
  McuStateNotify_FieldNumber_McuStatus = 3,
  McuStateNotify_FieldNumber_McuCode = 4,
  McuStateNotify_FieldNumber_McuMsg = 5,
};

GPB_FINAL @interface McuStateNotify : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *roomNo;
/** Test to see if @c roomNo has been set. */
@property(nonatomic, readwrite) BOOL hasRoomNo;

@property(nonatomic, readwrite) int32_t mcuMode;

@property(nonatomic, readwrite) BOOL hasMcuMode;
@property(nonatomic, readwrite) enum McuStatus mcuStatus;

@property(nonatomic, readwrite) BOOL hasMcuStatus;
@property(nonatomic, readwrite, copy, null_resettable) NSString *mcuCode;
/** Test to see if @c mcuCode has been set. */
@property(nonatomic, readwrite) BOOL hasMcuCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *mcuMsg;
/** Test to see if @c mcuMsg has been set. */
@property(nonatomic, readwrite) BOOL hasMcuMsg;

@end

#pragma mark - McuDiskNotify

typedef GPB_ENUM(McuDiskNotify_FieldNumber) {
  McuDiskNotify_FieldNumber_FreeDisk = 1,
  McuDiskNotify_FieldNumber_MinDisk = 2,
};

GPB_FINAL @interface McuDiskNotify : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *freeDisk;
/** Test to see if @c freeDisk has been set. */
@property(nonatomic, readwrite) BOOL hasFreeDisk;

@property(nonatomic, readwrite, copy, null_resettable) NSString *minDisk;
/** Test to see if @c minDisk has been set. */
@property(nonatomic, readwrite) BOOL hasMinDisk;

@end

#pragma mark - RoomConferenceNotify

typedef GPB_ENUM(RoomConferenceNotify_FieldNumber) {
  RoomConferenceNotify_FieldNumber_State = 1,
};

/**
 * 盒子6小时会议结之前更新状态
 **/
GPB_FINAL @interface RoomConferenceNotify : GPBMessage

@property(nonatomic, readwrite) int32_t state;

@property(nonatomic, readwrite) BOOL hasState;
@end

#pragma mark - SetMemberExtendInfoHostRequest

typedef GPB_ENUM(SetMemberExtendInfoHostRequest_FieldNumber) {
  SetMemberExtendInfoHostRequest_FieldNumber_Token = 1,
  SetMemberExtendInfoHostRequest_FieldNumber_RoomId = 2,
  SetMemberExtendInfoHostRequest_FieldNumber_AccountId = 3,
  SetMemberExtendInfoHostRequest_FieldNumber_TargetId = 4,
  SetMemberExtendInfoHostRequest_FieldNumber_ExtendInfo = 5,
};

/**
 * 修改成员自定义信息
 **/
GPB_FINAL @interface SetMemberExtendInfoHostRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;
/** Test to see if @c token has been set. */
@property(nonatomic, readwrite) BOOL hasToken;

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

/** 操作账号ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountId;
/** Test to see if @c accountId has been set. */
@property(nonatomic, readwrite) BOOL hasAccountId;

/** 目标账号ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *targetId;
/** Test to see if @c targetId has been set. */
@property(nonatomic, readwrite) BOOL hasTargetId;

/** 自定义信息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *extendInfo;
/** Test to see if @c extendInfo has been set. */
@property(nonatomic, readwrite) BOOL hasExtendInfo;

@end

#pragma mark - KickoutExitNotify

typedef GPB_ENUM(KickoutExitNotify_FieldNumber) {
  KickoutExitNotify_FieldNumber_AccountId = 1,
  KickoutExitNotify_FieldNumber_AccountTokenId = 2,
};

/**
 * 被踢离开会议通知
 **/
GPB_FINAL @interface KickoutExitNotify : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *accountId;
/** Test to see if @c accountId has been set. */
@property(nonatomic, readwrite) BOOL hasAccountId;

/** 被踢的用户token_id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountTokenId;
/** Test to see if @c accountTokenId has been set. */
@property(nonatomic, readwrite) BOOL hasAccountTokenId;

@end

#pragma mark - McuStatusNotify

typedef GPB_ENUM(McuStatusNotify_FieldNumber) {
  McuStatusNotify_FieldNumber_RoomNo = 1,
  McuStatusNotify_FieldNumber_McuStatus = 2,
};

/**
 * MCU录制监控状态
 **/
GPB_FINAL @interface McuStatusNotify : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *roomNo;
/** Test to see if @c roomNo has been set. */
@property(nonatomic, readwrite) BOOL hasRoomNo;

/** 0 正常录制 1 录制异步 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mcuStatus;
/** Test to see if @c mcuStatus has been set. */
@property(nonatomic, readwrite) BOOL hasMcuStatus;

@end

#pragma mark - McuRunStateNotify

typedef GPB_ENUM(McuRunStateNotify_FieldNumber) {
  McuRunStateNotify_FieldNumber_RoomNo = 1,
  McuRunStateNotify_FieldNumber_McuStatus = 2,
  McuRunStateNotify_FieldNumber_McuMsg = 3,
  McuRunStateNotify_FieldNumber_McuMsgEn = 4,
};

/**
 * MCU录制监控状态
 **/
GPB_FINAL @interface McuRunStateNotify : GPBMessage

/** 房间号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomNo;
/** Test to see if @c roomNo has been set. */
@property(nonatomic, readwrite) BOOL hasRoomNo;

/** 0 正常录制 1 录制异常 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mcuStatus;
/** Test to see if @c mcuStatus has been set. */
@property(nonatomic, readwrite) BOOL hasMcuStatus;

/** 异常消息 ：  录制异常、资源不足 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mcuMsg;
/** Test to see if @c mcuMsg has been set. */
@property(nonatomic, readwrite) BOOL hasMcuMsg;

/** 异常消息 ：  录制异常、资源不足英文消息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mcuMsgEn;
/** Test to see if @c mcuMsgEn has been set. */
@property(nonatomic, readwrite) BOOL hasMcuMsgEn;

@end

#pragma mark - WebinarRoleNotify

typedef GPB_ENUM(WebinarRoleNotify_FieldNumber) {
  WebinarRoleNotify_FieldNumber_RoomId = 1,
  WebinarRoleNotify_FieldNumber_AccountId = 2,
  WebinarRoleNotify_FieldNumber_Role = 3,
};

/**
 * 设置成员为观众/嘉宾通知
 **/
GPB_FINAL @interface WebinarRoleNotify : GPBMessage

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

/** 账号ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountId;
/** Test to see if @c accountId has been set. */
@property(nonatomic, readwrite) BOOL hasAccountId;

/** 6:观众；其他嘉宾 */
@property(nonatomic, readwrite) int32_t role;

@property(nonatomic, readwrite) BOOL hasRole;
@end

#pragma mark - WebinarAudienceNumNotify

typedef GPB_ENUM(WebinarAudienceNumNotify_FieldNumber) {
  WebinarAudienceNumNotify_FieldNumber_RoomId = 1,
  WebinarAudienceNumNotify_FieldNumber_AudienceNum = 2,
};

/**
 * 观众数通知
 **/
GPB_FINAL @interface WebinarAudienceNumNotify : GPBMessage

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomId;
/** Test to see if @c roomId has been set. */
@property(nonatomic, readwrite) BOOL hasRoomId;

/** 观众数量 */
@property(nonatomic, readwrite) int32_t audienceNum;

@property(nonatomic, readwrite) BOOL hasAudienceNum;
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
